# Generated by Django 5.1.2 on 2024-12-01 03:37

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='videos', validators=[content.models.validate_mp4_extension])),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('hls', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
