# Generated by Django 5.1.2 on 2025-08-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_castmember_genre_video_release_year_video_cast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('FAILED', 'Failed')], default='Pending', max_length=20),
        ),
    ]
