# Generated by Django 5.1.2 on 2025-08-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='errors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
