# Generated by Django 5.1.2 on 2025-08-08 06:15

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_video_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='server_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('server', 'Server Path')], default='upload', max_length=12),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos', validators=[content.models.validate_mp4_extension]),
        ),
    ]
